runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /favicon\.ico
  static_files: static/res/favicon.ico
  upload: static/res/favicon\.ico
- url: /.*
  script: main.app

libraries:
- name: ssl
  version: "latest"
- name: MySQLdb
  version: 1.2.5

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- env/

beta_settings:
    cloud_sql_instances: various-plans:europe-west1:library